import type { Product } from '@/types';

export const allProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Leather Watch',
    description: 'A timeless piece with a genuine leather strap and stainless steel case. Perfect for any occasion.',
    price: 180.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Accessories',
    stock: 15,
  },
  {
    id: '2',
    name: 'Minimalist Desk Lamp',
    description: 'Sleek and modern LED desk lamp with adjustable brightness. Enhances any workspace.',
    price: 75.50,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Home Goods',
    stock: 25,
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft, breathable, and ethically made. A staple for any conscious wardrobe.',
    price: 35.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Apparel',
    stock: 50,
  },
  {
    id: '4',
    name: 'Insulated Travel Mug',
    description: 'Keeps your drinks hot or cold for hours. Spill-proof lid and durable design.',
    price: 28.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Kitchen',
    stock: 40,
  },
  {
    id: '5',
    name: 'Smart Fitness Tracker',
    description: 'Monitor your activity, sleep, and heart rate with this feature-packed smart tracker.',
    price: 120.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Electronics',
    stock: 18,
  },
  {
    id: '6',
    name: 'Aromatic Soy Candle',
    description: 'Hand-poured soy wax candle with a calming lavender and vanilla scent.',
    price: 22.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Home Goods',
    stock: 60,
  },
  {
    id: '7',
    name: 'Gourmet Coffee Beans',
    description: 'A rich and smooth blend of single-origin Arabica beans from Colombia.',
    price: 19.99,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Kitchen',
    stock: 35,
  },
  {
    id: '8',
    name: 'Canvas Backpack',
    description: 'Durable and stylish backpack with multiple compartments and a padded laptop sleeve.',
    price: 85.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Accessories',
    stock: 22,
  },
  {
    id: '9',
    name: 'Wireless Bluetooth Earbuds',
    description: 'High-fidelity sound, long battery life, and a comfortable, secure fit for an active lifestyle.',
    price: 95.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Electronics',
    stock: 30,
  },
  {
    id: '10',
    name: 'Linen Throw Blanket',
    description: 'A lightweight and cozy throw blanket, perfect for adding a touch of elegance to your living room.',
    price: 110.00,
    imageUrl: 'https://placehold.co/600x600',
    category: 'Home Goods',
    stock: 12,
  }
];
